CREATE TABLE IF NOT EXISTS resource_operation_status (
    OPERATION_ID VARCHAR(255) NOT NULL,
    RESOURCE_TEMPLATE_UUID VARCHAR(255) NOT NULL,
    SERVICE_ID VARCHAR(255) NOT NULL,
    ERROR_CODE VARCHAR(255),
    JOB_ID VARCHAR(255),
    OPER_TYPE VARCHAR(255),
    PROGRESS VARCHAR(255),
    RESOURCE_INSTANCE_ID VARCHAR(255),
    STATUS VARCHAR(255),
    STATUS_DESCRIPOTION VARCHAR(2000),
    PRIMARY KEY (OPERATION_ID, RESOURCE_TEMPLATE_UUID, SERVICE_ID)
);
